require:
  - rubocop-ast
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - .spec
    - 'bin/**/*'
    - 'db/**/*'
    - 'lib/tasks/cucumber.rake'
    - Rakefile

Layout/ArrayAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/ClassStructure:
  Categories:
    association:
      - has_many
      - has_one
    attribute_macros:
      - attr_accessor
      - attr_reader
      - attr_writer
    macros:
      - attributes
      - validates
      - validate
    module_inclusion:
      - include
      - prepend
      - extend
  Enabled: true
  ExpectedOrder:
    - module_inclusion
    - constants
    - association
    - public_attribute_macros
    - public_delegate
    - macros
    - public_class_methods
    - initializer
    - public_methods
    - protected_attribute_macros
    - protected_methods
    - private_attribute_macros
    - private_delegate
    - private_methods

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Max: 80
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/**/*'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  CountComments: false  # count full line comments?
  Exclude:
    - 'Rakefile'
    - 'config/initializers/*'
    - '**/*.rake'
    - 'spec/**/*.rb'

RSpec/ExampleLength:
  Max: 12

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never
